//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int f_id { get; set; }
        public System.DateTime flightTime { get; set; }
        public string flightStatus { get; set; }
        public string flightPilot { get; set; }
        public string flightType { get; set; }
        public int plane_id { get; set; }
        public string departure { get; set; }
        public string destination { get; set; }
        public decimal flightPrice { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
