//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        public Plane()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public Nullable<int> numOfBusSeats { get; set; }
        public Nullable<int> numOfEcoSeats { get; set; }
        public Nullable<int> numOfFirstClassSeats { get; set; }
        public Nullable<int> numOfPremiumSeats { get; set; }
    
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
