//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public string rStatus { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> seat_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> seatNo { get; set; }
        public int r_id { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual User User { get; set; }
    }
}
