//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public Seat()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int s_id { get; set; }
        public Nullable<decimal> seatPrice { get; set; }
        public string seatType { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
