//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int u_id { get; set; }
        public string u_name { get; set; }
        public string pwd { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string role { get; set; }
        public string pass_id { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
